export const FROM_PUBLISH = 'FROM_PUBLISH'

export const GET_CITY_LIST = 'GET_CITY_LIST'

export const SAVE_LOCATION = 'SAVE_LOCATION'

export const SAVE_CITY_NAME = 'SAVE_CITY_NAME'

export const SET_CITY_NAME = 'SET_CITY_NAME'

export const SAVE_IDENTITY_LIST = 'SAVE_IDENTITY_LIST'

export const CLASS_HAS_CHANGED = 'CLASS_HAS_CHANGED'
